version: "3.9"
services:
    api:
        build:
            context: ./backend
            # use Dockerfile.gpu when using a NVIDIA GPU
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/workspace
        depends_on:
            - redis
        working_dir: /workspace/backend
        environment:
            - BASE_URL
            - EMAIL_SENDER_ADDRESS
            - EMAIL_SENDER_PASSWORD
            - EMAIL_SENDER_HOST
            - ALLOWED_WEBHOOKS_FILE
        command: flask --app src/main --debug run --host 0.0.0.0 --port 3000
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "4321:4321"
        volumes:
            - .:/workspace
        depends_on:
            - api
        command: node ./dist/server/entry.mjs
    worker:
        build:
            context: ./backend
            # use Dockerfile.gpu when using a NVIDIA GPU
            dockerfile: Dockerfile
        volumes:
            - .:/workspace
        depends_on:
            - redis
        working_dir: /workspace/backend
        environment:
            - BASE_URL
            - EMAIL_SENDER_ADDRESS
            - EMAIL_SENDER_PASSWORD
            - EMAIL_SENDER_HOST
            - ALLOWED_WEBHOOKS_FILE
        command: rq worker --url redis://redis:6379 -c worker-settings
        # Uncomment the following lines when using a NVIDIA GPU
        # deploy:
        #     resources:
        #         reservations:
        #             devices:
        #                 - driver: nvidia
        #                   capabilities: [gpu]

    redis:
        image: redis
        ports:
            - "6379:6379"
